### ISSUE TITLE
Discord pfp max image size

### ISSUE THREAD

**Issue by p0358** [dayanch96/PFPViewer#1]
For Discord the max `size` param is `4096` while you seem to set it to just `1280`:
https://github.com/dayanch96/PFPViewer/blob/afe5071a82703f56bea4ee07fdf6dc596c39ccc4/Discord.x#L36

Therefore it is my suggestion to up it to `4096` to always retrieve the max possible resolution of the image (sometimes the pfp is actually this large, but if it's not, then it'll return the original resolution, it won't ever upscale it above original, it's similar to how it works on Twitter, though they have an alias `orig` or something like that for `4096`).

**Comment by dayanch96** [comment]
i didn’t know that. this value is extremely rare tho. is it worth to raise it from 1280 to 4096?

**Comment by p0358** [comment]
I think so, I've sometimes seen PFPs this big, so imo there's no reason to get lower-res picture in this case. Otherwise you can always have at the back of your head that it's downscaled version and stuff

**Comment by dayanch96** [comment]
Kk, ill update it later today. thanks

**Comment by dayanch96** [comment]
https://github.com/dayanch96/PFPViewer/releases/tag/v0.0.3
